name = "supaflare-worker"
main = 'index.js'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE", id = "9d7d8f2dbaaa41c0a51555b3a94b1103", preview_id = "9d7d8f2dbaaa41c0a51555b3a94b1103" },
]
