name = "supaflare-worker"
main = 'index.js'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE", id = "71b0dc84e2b478d2f6993300deb55adc", preview_id = "78c8caceaf6b4228aea01f725ef70527" },
]
